### ISSUE TITLE
Tarballs created with symlinks to non-existent targets do not work properly

### ISSUE THREAD

**Issue by waja** [pi-top/action-debian-package#12]
Hi there,

while trying this on https://github.com/waja/imapsync, I've spotted issues with symlinks which point to not existing locations:

Inside the tarball:
```
waja@packaging:/tmp/imapsync-1.945$ ls -la | grep ^l
lrwxrwxrwx  1 waja waja     18 Nov  8 16:40 dist -> imapsync-1.945ist2
lrwxrwxrwx  1 waja waja     34 Nov  8 16:40 FAQ -> imapsync-1.945AQ.d/FAQ.General.txt
lrwxrwxrwx  1 waja waja     38 Nov  8 16:40 INSTALL -> imapsync-1.945NSTALL.d/INSTALL.ANY.txt
lrwxrwxrwx  1 waja waja     19 Nov  8 16:40 README.txt -> imapsync-1.945EADME
```
Origin directory:
```
waja@packaging:/tmp/imapsync (github_ci)$ ls -la | grep ^l
lrwxrwxrwx  1 waja waja     21 Jul 16 17:23 FAQ -> FAQ.d/FAQ.General.txt
lrwxrwxrwx  1 waja waja     25 Jul 16 17:23 INSTALL -> INSTALL.d/INSTALL.ANY.txt
lrwxrwxrwx  1 waja waja      6 Jul 16 17:23 README.txt -> README
lrwxrwxrwx  1 waja waja      5 Jul 16 17:23 dist -> dist2
```

Thanks and with kind regard, Jan.

**Comment by m-roberts** [comment]
Based on [this](https://github.com/waja/imapsync/runs/1370393541?check_suite_focus=true) GitHub Action:
```
/usr/bin/docker exec imapsync tar --exclude-vcs --exclude ./debian --transform s/^./imapsync-1.945/ -cvzf /home/runner/work/imapsync/imapsync_1.945.orig.tar.gz -C /home/runner/work/imapsync/imapsync/ ./
```
is the command being run. Does this work locally? If not, what command do you require for this to work? It seems as though the quality of the package is not very good anyway - I can seeing a lot of other errors, that may indicate a problem with the source.

I am not sure how we can take any action on this Issue.

**Comment by waja** [comment]
> Based on [this](https://github.com/waja/imapsync/runs/1370393541?check_suite_focus=true) GitHub Action:
> 
> ```
> /usr/bin/docker exec imapsync tar --exclude-vcs --exclude ./debian --transform s/^./imapsync-1.945/ -cvzf /home/runner/work/imapsync/imapsync_1.945.orig.tar.gz -C /home/runner/work/imapsync/imapsync/ ./
> ```
> is the command being run. Does this work locally?

This is what I used to pack it manual and as you can see, the symlinks are broken:

> ```
> waja@packaging:/tmp/imapsync-1.945$ ls -la | grep ^l
> lrwxrwxrwx  1 waja waja     18 Nov  8 16:40 dist -> imapsync-1.945ist2
> lrwxrwxrwx  1 waja waja     34 Nov  8 16:40 FAQ -> imapsync-1.945AQ.d/FAQ.General.txt
> lrwxrwxrwx  1 waja waja     38 Nov  8 16:40 INSTALL -> imapsync-1.945NSTALL.d/INSTALL.ANY.txt
> lrwxrwxrwx  1 waja waja     19 Nov  8 16:40 README.txt -> imapsync-1.945EADME
> ```

> If not, what command do you require for this to work? It seems as though the quality of the package is not very good anyway - I can seeing a lot of other errors, that may indicate a problem with the source.

The problem ist not related to this package itself but to all upstream projects using symlinks.

> I am not sure how we can take any action on this Issue.  


I'm suggesting the following command:

```
/usr/bin/docker exec imapsync tar --exclude-vcs --exclude ./debian --transform s/^./imapsync-1.945/S -cvzf /home/runner/work/imapsync/imapsync_1.945.orig.tar.gz -C /home/runner/work/imapsync/imapsync/ ./
```

I'm preparing a PR.

**Comment by waja** [comment]
I've opened #13

**Comment by m-roberts** [comment]
Where can we find the standard Debian packaging tools' implementation of this?

**Comment by waja** [comment]
This is depending on the packaging way. But while thinking about it, I'm pretty sure this transition is not needed. Just the upstream tarball needs to have the correct filename naming schema. (See https://en.wikipedia.org/wiki/Debian_build_toolchain#Source_packages and https://www.debian.org/doc/manuals/debmake-doc/ch05.en.html#name-version). Opened #16 fixing this.
